import localFont from "next/font/local";
import Navigation from "./components/layout/navigation";
import "./globals.css";

const font = localFont({
  src: "../../public/font/DNF.otf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navigation />
        <div className="main">{children}</div>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
